/*
 * Copyright (C) 1999-2011 id Software LLC, a ZeniMax Media company.
 * Translated to Kotlin by Dr. Feederino with support of Claude Code
 *
 * This file is part of the Doom 3 Kotlin project.
 * Original source: neo/Game/ai/AI_events.cpp
 *
 * Doom 3 Source Code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Doom 3 Source Code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

package neo.Game.AI

import neo.Game.GameSys.Event.idEventDef

val AI_AllowDamage: idEventDef = idEventDef("allowDamage")
val AI_AllowHiddenMovement: idEventDef = idEventDef("allowHiddenMovement", "d")
val AI_AllowMovement: idEventDef = idEventDef("allowMovement", "f")
val AI_AnimTurn: idEventDef = idEventDef("animTurn", "f")
val AI_AttackMelee: idEventDef = idEventDef("attackMelee", "s", 'd')
val AI_AttackMissile: idEventDef = idEventDef("attackMissile", "s", 'e')
val AI_BecomeRagdoll: idEventDef = idEventDef("becomeRagdoll", null, 'd')
val AI_BecomeSolid: idEventDef = idEventDef("becomeSolid")
val AI_BeginAttack: idEventDef = idEventDef("attackBegin", "s")
val AI_Burn: idEventDef = idEventDef("burn")
val AI_CanBecomeSolid: idEventDef = idEventDef("canBecomeSolid", null, 'f')
val AI_CanHitEnemy: idEventDef = idEventDef("canHitEnemy", null, 'd')
val AI_CanHitEnemyFromAnim: idEventDef = idEventDef("canHitEnemyFromAnim", "s", 'd')
val AI_CanHitEnemyFromJoint: idEventDef = idEventDef("canHitEnemyFromJoint", "s", 'd')
val AI_CanReachEnemy: idEventDef = idEventDef("canReachEnemy", null, 'd')
val AI_CanReachEntity: idEventDef = idEventDef("canReachEntity", "E", 'd')
val AI_CanReachPosition: idEventDef = idEventDef("canReachPosition", "v", 'd')
val AI_CanSeeEntity: idEventDef = idEventDef("canSee", "E", 'd')
val AI_ChargeAttack: idEventDef = idEventDef("chargeAttack", "s")
val AI_ClearBurn: idEventDef = idEventDef("clearBurn")
val AI_ClearEnemy: idEventDef = idEventDef("clearEnemy")
val AI_ClearFlyOffset: idEventDef = idEventDef("clearFlyOffset")
val AI_ClosestReachableEnemyOfEntity: idEventDef = idEventDef("closestReachableEnemyOfEntity", "E", 'e')
val AI_CreateMissile: idEventDef = idEventDef("createMissile", "s", 'e')
val AI_DirectDamage: idEventDef = idEventDef("directDamage", "es")
val AI_DisableAFPush: idEventDef = idEventDef("disableAFPush")
val AI_DisableClip: idEventDef = idEventDef("disableClip")
val AI_DisableGravity: idEventDef = idEventDef("disableGravity")
val AI_EnableAFPush: idEventDef = idEventDef("enableAFPush")
val AI_EnableClip: idEventDef = idEventDef("enableClip")
val AI_EnableGravity: idEventDef = idEventDef("enableGravity")
val AI_EndAttack: idEventDef = idEventDef("attackEnd")
val AI_EnemyInCombatCone: idEventDef = idEventDef("enemyInCombatCone", "Ed", 'd')
val AI_EnemyPositionValid: idEventDef = idEventDef("enemyPositionValid", null, 'd')
val AI_EnemyRange: idEventDef = idEventDef("enemyRange", null, 'f')
val AI_EnemyRange2D: idEventDef = idEventDef("enemyRange2D", null, 'f')
val AI_EntityInAttackCone: idEventDef = idEventDef("entityInAttackCone", "E", 'd')
val AI_FaceEnemy: idEventDef = idEventDef("faceEnemy")
val AI_FaceEntity: idEventDef = idEventDef("faceEntity", "E")
val AI_FacingIdeal: idEventDef = idEventDef("facingIdeal", null, 'd')
val AI_FindActorsInBounds: idEventDef = idEventDef("findActorsInBounds", "vv", 'e')

/* **********************************************************************

 AI Events

 ***********************************************************************/
val AI_FindEnemy: idEventDef = idEventDef("findEnemy", "d", 'e')
val AI_FindEnemyAI: idEventDef = idEventDef("findEnemyAI", "d", 'e')
val AI_FindEnemyInCombatNodes: idEventDef = idEventDef("findEnemyInCombatNodes", null, 'e')
val AI_FireMissileAtTarget: idEventDef = idEventDef("fireMissileAtTarget", "ss", 'e')
val AI_GetClosestHiddenTarget: idEventDef = idEventDef("getClosestHiddenTarget", "s", 'e')
val AI_GetCombatNode: idEventDef = idEventDef("getCombatNode", null, 'e')
val AI_GetCurrentYaw: idEventDef = idEventDef("getCurrentYaw", null, 'f')
val AI_GetEnemy: idEventDef = idEventDef("getEnemy", null, 'e')
val AI_GetEnemyEyePos: idEventDef = idEventDef("getEnemyEyePos", null, 'v')
val AI_GetEnemyPos: idEventDef = idEventDef("getEnemyPos", null, 'v')
val AI_GetHealth: idEventDef = idEventDef("getHealth", null, 'f')
val AI_GetJumpVelocity: idEventDef = idEventDef("getJumpVelocity", "vff", 'v')
val AI_GetMoveType: idEventDef = idEventDef("getMoveType", null, 'd')
val AI_GetObstacle: idEventDef = idEventDef("getObstacle", null, 'e')
val AI_GetRandomTarget: idEventDef = idEventDef("getRandomTarget", "s", 'e')
val AI_GetReachableEntityPosition: idEventDef = idEventDef("getReachableEntityPosition", "e", 'v')
val AI_GetTalkTarget: idEventDef = idEventDef("getTalkTarget", null, 'e')
val AI_GetTurnDelta: idEventDef = idEventDef("getTurnDelta", null, 'f')
val AI_GetTurnRate: idEventDef = idEventDef("getTurnRate", null, 'f')
val AI_HeardSound: idEventDef = idEventDef("heardSound", "d", 'e')
val AI_IgnoreDamage: idEventDef = idEventDef("ignoreDamage")
val AI_JumpFrame: idEventDef = idEventDef("<jumpframe>")
val AI_KickObstacles: idEventDef = idEventDef("kickObstacles", "Ef")
val AI_Kill: idEventDef = idEventDef("kill")
val AI_LaunchMissile: idEventDef = idEventDef("launchMissile", "vv", 'e')
val AI_LocateEnemy: idEventDef = idEventDef("locateEnemy")
val AI_LookAtEnemy: idEventDef = idEventDef("lookAtEnemy", "f")
val AI_LookAtEntity: idEventDef = idEventDef("lookAt", "Ef")
val AI_MeleeAttackToJoint: idEventDef = idEventDef("meleeAttackToJoint", "ss", 'd')
val AI_MoveOutOfRange: idEventDef = idEventDef("moveOutOfRange", "ef")
val AI_MoveStatus: idEventDef = idEventDef("moveStatus", null, 'd')
val AI_MoveToAttackPosition: idEventDef = idEventDef("moveToAttackPosition", "es")
val AI_MoveToCover: idEventDef = idEventDef("moveToCover")
val AI_MoveToEnemy: idEventDef = idEventDef("moveToEnemy")
val AI_MoveToEnemyHeight: idEventDef = idEventDef("moveToEnemyHeight")
val AI_MoveToEntity: idEventDef = idEventDef("moveToEntity", "e")
val AI_MoveToPosition: idEventDef = idEventDef("moveToPosition", "v")
val AI_MuzzleFlash: idEventDef = idEventDef("muzzleFlash", "s")
val AI_NumSmokeEmitters: idEventDef = idEventDef("numSmokeEmitters", null, 'd')
val AI_PreBurn: idEventDef = idEventDef("preBurn")
val AI_PredictEnemyPos: idEventDef = idEventDef("predictEnemyPos", "f", 'v')
val AI_PushPointIntoAAS: idEventDef = idEventDef("pushPointIntoAAS", "v", 'v')
val AI_RadiusDamageFromJoint: idEventDef = idEventDef("radiusDamageFromJoint", "ss")
val AI_RandomPath: idEventDef = idEventDef("randomPath", null, 'e')
val AI_RealKill: idEventDef = idEventDef("<kill>")
val AI_RestoreMove: idEventDef = idEventDef("restoreMove")
val AI_SaveMove: idEventDef = idEventDef("saveMove")
val AI_SetEnemy: idEventDef = idEventDef("setEnemy", "E")
val AI_SetFlyOffset: idEventDef = idEventDef("setFlyOffset", "d")
val AI_SetFlySpeed: idEventDef = idEventDef("setFlySpeed", "f")
val AI_SetHealth: idEventDef = idEventDef("setHealth", "f")
val AI_SetJointMod: idEventDef = idEventDef("setBoneMod", "d")
val AI_SetMoveType: idEventDef = idEventDef("setMoveType", "d")
val AI_SetSmokeVisibility: idEventDef = idEventDef("setSmokeVisibility", "dd")
val AI_SetTalkState: idEventDef = idEventDef("setTalkState", "d")
val AI_SetTalkTarget: idEventDef = idEventDef("setTalkTarget", "E")
val AI_SetTurnRate: idEventDef = idEventDef("setTurnRate", "f")
val AI_Shrivel: idEventDef = idEventDef("shrivel", "f")
val AI_SlideTo: idEventDef = idEventDef("slideTo", "vf")
val AI_StopMove: idEventDef = idEventDef("stopMove")
val AI_StopRagdoll: idEventDef = idEventDef("stopRagdoll")
val AI_StopThinking: idEventDef = idEventDef("stopThinking")
val AI_TestAnimAttack: idEventDef = idEventDef("testAnimAttack", "s", 'd')
val AI_TestAnimMove: idEventDef = idEventDef("testAnimMove", "s", 'd')
val AI_TestAnimMoveTowardEnemy: idEventDef = idEventDef("testAnimMoveTowardEnemy", "s", 'd')
val AI_TestChargeAttack: idEventDef = idEventDef("testChargeAttack", null, 'f')
val AI_TestMeleeAttack: idEventDef = idEventDef("testMeleeAttack", null, 'd')
val AI_TestMoveToPosition: idEventDef = idEventDef("testMoveToPosition", "v", 'd')
val AI_ThrowAF: idEventDef = idEventDef("throwAF")
val AI_ThrowMoveable: idEventDef = idEventDef("throwMoveable")
val AI_TravelDistanceBetweenEntities: idEventDef = idEventDef("travelDistanceBetweenEntities", "ee", 'f')
val AI_TravelDistanceBetweenPoints: idEventDef = idEventDef("travelDistanceBetweenPoints", "vv", 'f')
val AI_TravelDistanceToEntity: idEventDef = idEventDef("travelDistanceToEntity", "e", 'f')
val AI_TravelDistanceToPoint: idEventDef = idEventDef("travelDistanceToPoint", "v", 'f')
val AI_TriggerParticles: idEventDef = idEventDef("triggerParticles", "s")
val AI_TurnTo: idEventDef = idEventDef("turnTo", "f")
val AI_TurnToEntity: idEventDef = idEventDef("turnToEntity", "E")
val AI_TurnToPos: idEventDef = idEventDef("turnToPos", "v")
val AI_WaitAction: idEventDef = idEventDef("waitAction", "s")
val AI_WaitMove: idEventDef = idEventDef("waitMove")
val AI_WakeOnFlashlight: idEventDef = idEventDef("wakeOnFlashlight", "d")
val AI_Wander: idEventDef = idEventDef("wander")
