/*
 * Copyright (C) 1999-2011 id Software LLC, a ZeniMax Media company.
 * Translated to Kotlin by Dr. Feederino with support of Claude Code
 *
 * This file is part of the Doom 3 Kotlin project.
 * Original source: neo/game/gamesys/NoGameTypeInfo.h
 *
 * Doom 3 Source Code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Doom 3 Source Code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Doom 3 Source Code. If not, see <http://www.gnu.org/licenses/>.
 */

package neo.Game.GameSys

/*
 ===================================================================================

 This file has been generated with the Type Info Generator v1.0 (c) 2004 id Software

 ===================================================================================
 */

/**
 * Stub type info data used in release builds (no runtime type introspection).
 * In debug builds, the full GameTypeInfo.h would be generated by the TypeInfoGen tool
 * and would contain actual class/enum/constant metadata.
 */
object NoGameTypeInfo {

    // NOTE: C++ struct field order: name, type, value
    class constantInfo_t(var name: String?, var type: String?, var value: String?)

    // NOTE: C++ struct field order: name, value
    class enumValueInfo_t(var name: String?, var value: Int)

    // NOTE: C++ struct field order: typeName, values
    class enumTypeInfo_t(var typeName: String?, var values: Array<enumValueInfo_t?>?)

    // NOTE: C++ struct field order: type, name, offset, size
    class classVariableInfo_t {
        var type: String? = null
        var name: String? = null
        var offset: Int = 0
        var size: Int = 0
    }

    // NOTE: C++ struct field order: typeName, superType, size, variables
    class classTypeInfo_t(
        var typeName: String?,
        var superType: String?,
        var size: Int,
        var variables: Array<classVariableInfo_t>?
    )

    // Empty sentinel arrays — null-terminated like C++ originals
    var enumTypeInfo: Array<enumTypeInfo_t> = arrayOf(
        enumTypeInfo_t(null, null)
    )

    var classTypeInfo: Array<classTypeInfo_t> = arrayOf(
        classTypeInfo_t(null, null, 0, null)
    )
}
